version: '3.3'

services:
  reverse-proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/htpasswd:/etc/nginx/htpasswd
      - ../build:/app/web
    extra_hosts:
      - "host.docker.internal:host-gateway"